workspace(name = "morris")

load("//:deps.bzl", "whisper", "extra_bazel_deps", "extra_tools", "libtorch", "onnx", "pybind", "sdl")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

whisper()
extra_bazel_deps()
#torch_deps()

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies(cmake_version = "3.26.4")


load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

sdl()

libtorch()

onnx()

pybind()
load("@pybind11_bazel//:python_configure.bzl", "python_configure")
python_configure(name = "local_config_python")

extra_tools()

'''new_local_repository(
    name = "libtorch_archive",
    build_file = "@//:libtorch.BUILD",
    path = "/home/jonas/Downloads/libtorch",
)'''